# Generated by Django 3.2.18 on 2023-04-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cnp',
            fields=[
                ('cnp', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
